;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-beginning-of-statement
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        count-words-region
        end-of-visual-line
        handle-switch-frame
        helm-for-files
        kill-whole-line-move-up
        ))

(setq mc/cmds-to-run-once
      '(
        mac-mwheel-scroll
        mark-paragraph
        mark-whole-buffer
        ))
